server:
  port: 18080

spring:
  application:
    name: member-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        service: ${spring.application.name}
        enabled: true
        group: tome
      username: nacos
      password: nacos
      server-addr: 127.0.0.1:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
