apiVersion: v1
kind: Service
metadata:
  name: member
  namespace: tome
  labels:
    app: member
spec:
  type: NodePort
  selector:
    app: member
  ports:
    - port: 80
      targetPort: http-server