apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tome-admin-role-binding
  namespace: tome
roleRef:
  kind: Role
  name: tome-admin-rule
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: tome-admin
    namespace: tome
